### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by dcurgz** [ryancole/LeagueReplayReader#1]
I'd like to ask if you managed to find this out yourself or if there is an existing resource. I'd like to make a game replay parser myself and this project has been the closest thing I've found to a similar attempt. Also, if you have the time (while I'm aware it's likely out of date), could you quickly summarise how you managed to parse the data (given you figured it out yourself), or let me know how you found it out?

Thanks :)

**Comment by ryancole** [comment]
I did this all myself. I used [IDA](https://www.hex-rays.com/products/ida/) to decompile and reverse engineer the League client. I also used IDA for run-time debugging of the League client.

Back when I wrote this, the League client also doubled as the replay client, which I believe is still the case. Replays were literally just the game data saved to a file. Watching a replay simply meant feeding back into the client that data. There was additional functionality added, to the League client, to facilitate loading the replay file, etc. That is the code that I located and reverse engineered to write LeagueReplayReader.

It really was not too difficult, if I recall. I think I just opened up League in IDA and searched around for hard coded string values that appeared when watching a replay.  Once I found that, I back tracked up the path of execution until I found where the client was loading the replay file. At the time of writing this, the League client was pretty simple to debug, as it's merely a viewer for network events since everything is server-provided. So, the game had your typical init functions, followed by main game loop. Finding those functions didn't take long.

This code just breaks open the replay file down into its raw parts. It does not actually dive into the keyframes, etc, and make sense of the game events. That was next on my list, but Riot killed their replay feature and so I stopped working on it. I bet there are detailed write ups out there on various hacking forums that detail all the actual replay data.

I doubt this works, still. I see that replay files are still `.rofl`, though. The format is likely the same, but I assume there has been features added since this.

**Comment by jaspinegz** [comment]
Awesome, thanks for getting back to me! I'll update you on any related progress I make. :)

**Comment by doivosevic** [comment]
Hey @ryancole . Thank you so much for this project! I'm trying to collect all the efforts regarding parsing .rofl files https://github.com/Kungitoo/LolReplayParser2020 and this project is the only one I could get to work immediately on the latest .rofl files (at least it seems to be working). Now I'm trying to find any meaning in the bits there. Do you have any idea if they stored some data as actual strings in the keyframes or is it all just bits. I tried doing a naive conversion to ASCII or UTF8 but it really all seems like noise. If they store champions and items as bits, do you have any idea how? I tried taking a keyframe and per https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment looking into a replay with Warwick in it I would expect to find "57 61 72 77 69 63 6b" in there or at least some part of the bits but I don't think they are there anymore. Do you have some sample code which finds some noteable string? I'm afraid I'm checking for wrong bit order or something

**Comment by ryancole** [comment]
My code here unpacks the .rofl file so that you can proceed to read the chunk and keyframe files. The chunk and keyframes contain the data for the replay client so that it can reproduce what took place in the game.

You can find the answer to your question about strings by opening a chunk or keyframe file up in notepad and see if you can see any readable text. I don't recall if they do or not - it has been a long time.

My assumption would be that most everything is stored in these chunks and keyframes as identifiers - not strings - and the client knows how to map those identifiers to the items, champions, actions, etc. This would keep the replay files small, but also keeps data packet payload sizes small for the spectator client, which uses the same data.

I wish I had that loldevs link you pasted back when I was doing this code. That would have helped. I assume the structure is still largely the same. I don't have any sample code. One think I was doing back in the day, and you can try, is to crack open the league client with a disassembler / decompiler / debugger, like IDA, and try to locate where it loads up the .rofl file. This is how I did all of my work.

**Comment by ryancole** [comment]
Oh yea, wow, that link has tons of great info. Here's a good explanation of the chunks and keyframes: https://github.com/loldevs/leaguespec/wiki/General-Binary-Format

Makes me want to take a stab at parsing those, too. Although I bet the format has changed quite a bit, actually. The info in there is from patch 4.X! That's back when there were still runes and stuff. Now there's all sorts of new stuff, like the emotes, champion mastery level and all that. So I bet the structure is quite different.

**Comment by doivosevic** [comment]
The problem is that I cannot find any of the patterns described in those loldevs files. Even the keyframe header doesn't match (I think the beginnings of the keyframe files differ each time). I did some pattern matching trying to find repeating patterns between games and different keyframes from same game but I'm having a hard time figuring out a meaning behind them. I was expecting to use the item key codes and find those bits in the keyframes but I'm not getting results so maybe they encode items with some other scheme. What I understand is that items only appear from the 2nd or 3rd keyframe. I'm still reluctant to try using a dissassembler because I haven't done anything like that before

**Comment by mlobl** [comment]
I've been schmoozing with @Kungitoo and I just posted some code that'll parse the keyframes and chunk headers. Just not sure how to decrypt said keyframes and chunks anymore.
https://gist.github.com/lukegb/d2997a5fc7970ce6e1e1

**Comment by ryancole** [comment]
A debugger attaches to the lol client should tell you how they’re
decrypting the data

**Comment by doivosevic** [comment]
I've hooked up with IDA Pro to the exe and I'm trying to find where they load the replay file. Do you have any idea @ryancole which keyword to search for? I tried modifying the replay binary and then I forced the "replay corrupt" error but I still cannot find where it's invoked

**Comment by ryancole** [comment]
@Kungitoo Nice. You're on the path to reverse engineering! You can use IDA to attach to a running process or even launch a process. In the case of League and viewing a replay, I used to launch the process so that I can see the initial steps the game exe takes when entering replay mode and parsing the replay file.

If you'd like to launch a League process, you will need to figure out the correct parameters to pass into the game exe for viewing a replay file. Back in the day, I did this in a very hack-ish way - I made a C# program that spit out all the command line arguments passed to it, and I just replaced the league exe with my exe. Then, I launched a replay and looked at the command lines that the launcher passes to the game exe for viewing a replay. With that information, you can tell IDA to start up the game exe.

Attaching to a running process is easier - you just launch league and then in IDA select the process to attach to. You can do this, but you might miss the code that runs inbetween the time you launch the game and tell IDA to attach. So if that code is important to you, launching the process is the better route.

Once IDA is debugging the game exe, using either of the 2 above steps, you can locate that code you mentioned - a corrupt replay - and put a break point in it. That code actually sounds like a good spot, since it's clearly trying to parse the replay file and is finding that its corrupt. IDA should stop when it hits your break point and then you can just take a look at the call stack. That call stack will tell you which functions called the function that you're in. So, at this point you'd just manually begin the process of walking up the call stack, documenting the functions as you go, until you begin to paint a picture of what the code is doing.

A word of advice: save your IDA project (with your comments, and defined function names, etc). Also make sure when you're debugging, keep a copy of the game exe that you're working against. League patches like every week and that will change all the offsets and your IDA comments, etc. So be sure to just work against a single copy for awhile - not against the live version of the game. Eventually you'll memorize the code enough to finger print specific areas in the code and relocate them across game versions.

Good luck! It's a lot of work
